version-tags: &version-tags
    tags:
        only: /v\d+\.\d+\.\d+(-(alpha|beta|rc|dev|post)\d+)?/

version: 2.1
executors:
    my-executor:
        docker:
            - image: circleci/python:3.7.8
              auth:
                username: jonathf
                password: $DOCKERHUB_PASSWORD
        working_directory: /home/circleci/project

jobs:
    test:
        executor: my-executor
        steps:
            - checkout
            - restore_cache:
                keys:
                    - deps-{{ checksum "poetry.lock"}}
                    - deps-
            - run:
                name: "Installation"
                command: |
                    python3 -m venv /home/circleci/venv
                    source /home/circleci/venv/bin/activate
                    pip install poetry==1.0.5
                    poetry install
            - save_cache:
                key: deps-{{ checksum "poetry.lock"}}
                paths:
                    - /home/circleci/venv
            - run:
                name: "Run pylint"
                command: |
                    source /home/circleci/venv/bin/activate
                    pylint --rcfile=.pylintrc -E numpoly
            - run:
                name: "Run pydocstyle"
                command: |
                    source /home/circleci/venv/bin/activate
                    pydocstyle numpoly
            - run:
                name: "Run tests"
                command: |
                    source /home/circleci/venv/bin/activate
                    coverage run --source numpoly/ --module pytest --doctest-modules numpoly/ test/ docs/*.rst README.rst
                    codecov
                    coverage report --show-missing --fail-under=100
            - run:
                name: "Run Sphinx build"
                command: |
                    source /home/circleci/venv/bin/activate
                    sphinx-build docs/ docs/.build -b html -n -v --color -T -W --keep-going
    deploy:
        executor: my-executor
        steps:
            - checkout
            - restore_cache:
                keys:
                    - deps-{{ checksum "poetry.lock"}}
            - run:
                name: "Installation"
                command: |
                    source /home/circleci/venv/bin/activate
                    poetry install
            - run:
                name: "Verify tag version"
                command: |
                    PROJECT_TAG=$(cat pyproject.toml \
                        | grep 'version\s*=' \
                        | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-z0-9]\+\)\{0,1\}')
                    echo "$CIRCLE_TAG == v$PROJECT_TAG"
                    test "$CIRCLE_TAG" = "v$PROJECT_TAG"
            - run:
                name: "Publish to PyPI"
                command: |
                    source /home/circleci/venv/bin/activate
                    poetry publish --build -u jonathf -p $PYPI_PASSWORD -n

workflows:
    version: 2.1
    workflow:
        jobs:
            - test:
                filters:
                    <<: *version-tags
            - deploy:
                requires:
                    - test
                filters:
                    <<: *version-tags
                    branches:
                        ignore: /.*/
